-- Plaza CRM schema (project: zhxwkntrndaeqtkmbtsh) — isolated from Plazacore
-- Owner-only access: every authenticated Plaza user sees the firm's deals.

create table if not exists deals (
  id                  bigint generated by default as identity primary key,
  project_no          text unique,
  name                text not null,
  client              text,
  contact_name        text,
  contact_email       text,
  stage               text not null default 'Lead',
  value_note          text,
  amount              numeric,
  priority            text default 'MEDIUM',
  proposal_sent_date  date,
  last_contact_date   date,
  next_action         text,
  next_action_due     date,
  evidence            text,
  dropbox_folder      text,
  notes               text,
  keywords            text[] default '{}',
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

create table if not exists activities (
  id           bigint generated by default as identity primary key,
  deal_id      bigint not null references deals(id) on delete cascade,
  kind         text not null,
  summary      text,
  body         text,
  occurred_at  timestamptz default now(),
  created_by   text
);
create index if not exists idx_act_deal on activities(deal_id, occurred_at desc);

-- keep updated_at honest
create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_deals_touch on deals;
create trigger trg_deals_touch before update on deals
for each row execute function touch_updated_at();

-- ---------------- RLS: authenticated-only, no anonymous access ----------------
alter table deals      enable row level security;
alter table activities enable row level security;

drop policy if exists deals_auth_all on deals;
create policy deals_auth_all on deals
  for all to authenticated using (true) with check (true);

drop policy if exists acts_auth_all on activities;
create policy acts_auth_all on activities
  for all to authenticated using (true) with check (true);

-- explicitly ensure the anon role has no table rights
revoke all on deals      from anon;
revoke all on activities from anon;
